### ISSUE TITLE
Artifacts contains empty data and 0 Kb size

### ISSUE THREAD

**Issue by dhruvappstack** [maxirmx/Dist_zlib#2]
I download the artificats files to compile nextcloud client for windows . All the files contains in debug or release folders are 0 Kb size and contains no data. Please provided actual files so that i can build nextcloud client.

**Comment by maxirmx** [comment]
Hello and thank you for yor message

I can see that 7z files contain artifacts.  Could you please provide more details and\or attach a screenshot.

Thank you
Maxim
